<big>
<h1>Submitted By - Ishan Ojha 
Assignment no 2 
Cs-21 </h1></big>

In [1]:
#Installing tensor flow 2.19.0 @latest  not 1.13.1 because TensorFlow 1.13.1 is no longer available on the latest versions of Python and pip.
import tensorflow as tf
hello = tf.constant("Hello TensorFlow!")
print(hello.numpy())

b'Hello TensorFlow!'


<h2>add operation and multiply operation and  understanding graph  </h2>

In [2]:

import tensorflow as tf
x = 2
y = 3
z = tf.add(x, y, name='Add')
print(z)
graph = tf.Graph()
with graph.as_default():    
    z = tf.add(x, y, name='Add')
a = tf.multiply(3,3)
print(a)
a = tf.multiply(3, 3)  
print(a.numpy()) 
x = tf.constant(13)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
9


<h2>Math operations in TensorFlow </h2>

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Input
import numpy as np
x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])


In [4]:
#adding two numbers:
sum = tf.add(x,y)
sum.numpy()


array([4., 4., 4.], dtype=float32)

In [5]:
#subtracting two numbers
difference = tf.subtract(x,y)
difference.numpy()


array([-2.,  0.,  2.], dtype=float32)

In [6]:
#multiplying two numbers 
product = tf.multiply(x,y)
product.numpy()


array([3., 4., 3.], dtype=float32)

In [7]:
#dividing two numbres
division = tf.divide(x,y)
division.numpy()


array([0.33333334, 1.        , 3.        ], dtype=float32)

In [8]:
#dot product of x and y 
dot_product = tf.reduce_sum(tf.multiply(x, y))
dot_product.numpy()


10.0

In [9]:
#index of min and max elements 
x = tf.constant([10, 0, 13, 9])
tf.argmin(x).numpy()


1

In [10]:
tf.argmax(x).numpy()


2

In [11]:
#squared difference finding 
x = tf.Variable([1,3,5,7,11])
y = tf.Variable([1])
tf.math.squared_difference(x,y).numpy()
#typecasting
print (x.dtype)
x = tf.cast(x, dtype=tf.float32)
print (x.dtype)


<dtype: 'int32'>
<dtype: 'float32'>


In [12]:
x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]


In [13]:
#concatenation of two matrices row wise and col wise 
tf.concat([x, y], 0).numpy()


array([[3, 6, 9],
       [7, 7, 7],
       [4, 5, 6],
       [5, 5, 5]])

In [14]:
tf.concat([x, y], 1).numpy()


array([[3, 6, 9, 4, 5, 6],
       [7, 7, 7, 5, 5, 5]])

In [15]:
#stacking the matrix using the stack funciton 
tf.stack(x, axis=1).numpy()


array([[3, 7],
       [6, 7],
       [9, 7]])

In [16]:
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
x.numpy()


array([[1., 5.],
       [2., 3.]], dtype=float32)

In [17]:
#performing the reduce mean operation 
tf.reduce_mean(input_tensor=x).numpy()


2.75

In [18]:
tf.reduce_mean(input_tensor=x, axis=0).numpy()

array([1.5, 4. ], dtype=float32)

In [19]:
tf.reduce_mean(input_tensor=x, axis=1, keepdims=True).numpy()


array([[3. ],
       [2.5]], dtype=float32)

In [20]:
#Drawing random values from the probability distributions:
tf.random.normal(shape=(3,2), mean=10.0, stddev=2.0).numpy()
tf.random.uniform(shape = (3,2), minval=0, maxval=None, dtype=tf.float32,).numpy()


array([[0.23677158, 0.98215866],
       [0.23439384, 0.03067482],
       [0.23570013, 0.63890517]], dtype=float32)

In [21]:
#softmax probabilities 
x = tf.constant([7., 2., 5.])
tf.nn.softmax(x).numpy()

array([0.8756006 , 0.00589975, 0.11849965], dtype=float32)

In [22]:
def square(x):
    return tf.multiply(x, x)
with tf.GradientTape(persistent=True) as tape:
    print(square(6.).numpy())


36.0


 <h2>TensorFlow 2.0 and Keras</h2>

Building Compiling training and evaluating a model in keras 

In [23]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Input
import numpy as np

# Generating some sample data set
np.random.seed(42)
data = np.random.rand(100, 7)   # 100 samples, 7 features
labels = np.random.randint(0, 2, 100)  # Binary classification (0 or 1)

data_test = np.random.rand(20, 7)  # 20 test samples
labels_test = np.random.randint(0, 2, 20)



In [24]:
# 1. Defining the Model (Sequential API)
model_seq = Sequential()
model_seq.add(Dense(13, input_dim=7, activation='relu'))
model_seq.add(Dense(7, activation='relu'))
model_seq.add(Dense(1, activation='sigmoid'))

# 2. Compiling the Model
model_seq.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

# 3. Training the Model
model_seq.fit(x=data, y=labels, epochs=10, batch_size=10)

#4. Evaluating the Model
train_loss, train_acc = model_seq.evaluate(x=data, y=labels)
test_loss, test_acc = model_seq.evaluate(x=data_test, y=labels_test)

print(f"Training Accuracy: {train_acc:.4f}, Training Loss: {train_loss:.4f}")
print(f"Test Accuracy: {test_acc:.4f}, Test Loss: {test_loss:.4f}")



Epoch 1/10


C:\Users\Nitro\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5163 - loss: 0.7059  
Epoch 2/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5969 - loss: 0.6927 
Epoch 3/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5349 - loss: 0.6936 
Epoch 4/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6921 
Epoch 5/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5720 - loss: 0.6912 
Epoch 6/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5123 - loss: 0.6950 
Epoch 7/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4985 - loss: 0.6944 
Epoch 8/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4683 - loss: 0.6980 
Epoch 9/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4807 - loss: 0.7001 
Epoch 10/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5254 - loss: 0.6970 
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5505 - loss: 0.6918 
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5500 - loss: 0.6825
Training Accura

In [25]:
# Functional API Model 
# Define input layer
input_layer = Input(shape=(7,))

# Define hidden layers
layer1 = Dense(13, activation='relu')(input_layer)
layer2 = Dense(7, activation='relu')(layer1)

# Define output layer
output_layer = Dense(1, activation='sigmoid')(layer2)

# Create the model
model_func = Model(inputs=input_layer, outputs=output_layer)

# Compile the functional model
model_func.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

# Train the functional model
model_func.fit(x=data, y=labels, epochs=10, batch_size=10)

# Evaluate the functional model
train_loss, train_acc = model_func.evaluate(x=data, y=labels)
test_loss, test_acc = model_func.evaluate(x=data_test, y=labels_test)

print(f"[Functional] Training Accuracy: {train_acc:.4f}, Training Loss: {train_loss:.4f}")
print(f"[Functional] Test Accuracy: {test_acc:.4f}, Test Loss: {test_loss:.4f}")


Epoch 1/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5514 - loss: 0.6812  
Epoch 2/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5862 - loss: 0.6699 
Epoch 3/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5017 - loss: 0.6927 
Epoch 4/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5299 - loss: 0.6831 
Epoch 5/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5661 - loss: 0.6842 
Epoch 6/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5260 - loss: 0.6904 
Epoch 7/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5660 - loss: 0.6654 
Epoch 8/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4505 - loss: 0.7016 
Epoch 9/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4872 - loss: 0.6973 
Epoch 10/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5725 - loss: 0.6792 
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5401 - loss: 0.6766 
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.4000 - loss: 0.7325
[Fun

<h2>MNIST digit classification using
TensorFlow 2.0</h2>

In [26]:
#Importing the libraries
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf
print (tf.__version__)

2.19.0


In [27]:
#loading the dataset
mnist =  tf.keras.datasets.mnist

In [28]:
# creating a train and test set:
(x_train,y_train), (x_test, y_test) = mnist.load_data()
# Normalizing the x values by diving with maximum value of x which is 255 and convert them to float:
x_train, x_test = tf.cast(x_train/255.0, tf.float32), tf.cast(x_test/255.0, tf.float32)
# converting y values to int:
y_train, y_test = tf.cast(y_train,tf.int64),tf.cast(y_test,tf.int64)
# Defining the sequential model:
model = tf.keras.models.Sequential()

In [29]:
# Adding the layers. applying ReLU activation at the first two layers 
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(256, activation="relu"))
model.add(tf.keras.layers.Dense(128, activation="relu"))
#applying softmax function in the final layer
model.add(tf.keras.layers.Dense(10, activation="softmax"))


In [30]:
# Compiling the model with Stochastic Gradient Descent, that is 'sgd' 

model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# Train the model for 10 epochs with batch_size as 32:
model.fit(x_train, y_train, batch_size=32, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7349 - loss: 0.9835
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9156 - loss: 0.2942
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9338 - loss: 0.2326
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9444 - loss: 0.1974
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9489 - loss: 0.1765
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9561 - loss: 0.1543
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9628 - loss: 0.1331
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9644 - loss: 0.1251
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9693 - loss: 0.1113
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9694 - loss: 0.1085


In [31]:
#evaluating the model on test sets
model.evaluate(x_test, y_test)


313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.9608 - loss: 0.1312


[0.1113937497138977, 0.9670000076293945]