<big>
<h1>Submitted By - Ishan Ojha 
Assignment no 2 
Cs-21 </h1></big>

In [ ]:
#Installing tensor flow 2.19.0 @latest  not 1.13.1 because TensorFlow 1.13.1 is no longer available on the latest versions of Python and pip.
import tensorflow as tf
hello = tf.constant("Hello TensorFlow!")
print(hello.numpy())

b'Hello TensorFlow!'


<h2>add operation and multiply operation and  understanding graph  </h2>

In [ ]:

import tensorflow as tf
x = 2
y = 3
z = tf.add(x, y, name='Add')
print(z)
graph = tf.Graph()
with graph.as_default():    
    z = tf.add(x, y, name='Add')
a = tf.multiply(3,3)
print(a)
a = tf.multiply(3, 3)  
print(a.numpy()) 
x = tf.constant(13)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
9


<h2>Math operations in TensorFlow </h2>

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Input
import numpy as np
x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])


In [2]:
sum = tf.add(x,y)
sum.numpy()


array([4., 4., 4.], dtype=float32)

In [3]:
difference = tf.subtract(x,y)
difference.numpy()


array([-2.,  0.,  2.], dtype=float32)

In [4]:
product = tf.multiply(x,y)
product.numpy()


array([3., 4., 3.], dtype=float32)

In [5]:
division = tf.divide(x,y)
division.numpy()


array([0.33333334, 1.        , 3.        ], dtype=float32)

In [6]:
dot_product = tf.reduce_sum(tf.multiply(x, y))
dot_product.numpy()


10.0

In [8]:
x = tf.constant([10, 0, 13, 9])
tf.argmin(x).numpy()


1

In [9]:
tf.argmax(x).numpy()


2

In [10]:
x = tf.Variable([1,3,5,7,11])
y = tf.Variable([1])
tf.math.squared_difference(x,y).numpy()
print (x.dtype)
x = tf.cast(x, dtype=tf.float32)
print (x.dtype)


<dtype: 'int32'>
<dtype: 'float32'>


In [11]:
x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]


In [12]:
tf.concat([x, y], 0).numpy()


array([[3, 6, 9],
       [7, 7, 7],
       [4, 5, 6],
       [5, 5, 5]])

In [13]:
tf.concat([x, y], 1).numpy()


array([[3, 6, 9, 4, 5, 6],
       [7, 7, 7, 5, 5, 5]])

In [14]:
tf.stack(x, axis=1).numpy()


array([[3, 7],
       [6, 7],
       [9, 7]])

In [15]:
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
x.numpy()


array([[1., 5.],
       [2., 3.]], dtype=float32)

In [16]:
tf.reduce_mean(input_tensor=x).numpy()


2.75

In [17]:
tf.reduce_mean(input_tensor=x, axis=0).numpy()

array([1.5, 4. ], dtype=float32)

In [18]:
tf.reduce_mean(input_tensor=x, axis=1, keepdims=True).numpy()


array([[3. ],
       [2.5]], dtype=float32)

In [19]:
tf.random.normal(shape=(3,2), mean=10.0, stddev=2.0).numpy()
tf.random.uniform(shape = (3,2), minval=0, maxval=None, dtype=tf.float32,).numpy()


array([[0.7235416 , 0.06477988],
       [0.93473744, 0.7365694 ],
       [0.70054436, 0.88658   ]], dtype=float32)

In [20]:
x = tf.constant([7., 2., 5.])
tf.nn.softmax(x).numpy()

array([0.8756006 , 0.00589975, 0.11849965], dtype=float32)

In [21]:
def square(x):
    return tf.multiply(x, x)
with tf.GradientTape(persistent=True) as tape:
    print(square(6.).numpy())


36.0


 <h2>TensorFlow 2.0 and Keras</h2>

Building Compiling training and evaluating a model in keras 

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Input
import numpy as np

# Generating some sample data set
np.random.seed(42)
data = np.random.rand(100, 7)   # 100 samples, 7 features
labels = np.random.randint(0, 2, 100)  # Binary classification (0 or 1)

data_test = np.random.rand(20, 7)  # 20 test samples
labels_test = np.random.randint(0, 2, 20)



In [4]:
# 1. Defining the Model (Sequential API)
model_seq = Sequential()
model_seq.add(Dense(13, input_dim=7, activation='relu'))
model_seq.add(Dense(7, activation='relu'))
model_seq.add(Dense(1, activation='sigmoid'))

# 2. Compiling the Model
model_seq.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

# 3. Training the Model
model_seq.fit(x=data, y=labels, epochs=10, batch_size=10)

#4. Evaluating the Model
train_loss, train_acc = model_seq.evaluate(x=data, y=labels)
test_loss, test_acc = model_seq.evaluate(x=data_test, y=labels_test)

print(f"Training Accuracy: {train_acc:.4f}, Training Loss: {train_loss:.4f}")
print(f"Test Accuracy: {test_acc:.4f}, Test Loss: {test_loss:.4f}")



Epoch 1/10


C:\Users\Nitro\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5094 - loss: 0.7483  
Epoch 2/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5803 - loss: 0.7032 
Epoch 3/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5347 - loss: 0.7169 
Epoch 4/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4515 - loss: 0.7478 
Epoch 5/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4870 - loss: 0.7198 
Epoch 6/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5070 - loss: 0.7154 
Epoch 7/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4838 - loss: 0.7082 
Epoch 8/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5527 - loss: 0.6988 
Epoch 9/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5438 - loss: 0.7040 
Epoch 10/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5347 - loss: 0.7019 
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5648 - loss: 0.6878 
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.4000 - loss: 0.7247
Training Accura

In [5]:
# Functional API Model 
# Define input layer
input_layer = Input(shape=(7,))

# Define hidden layers
layer1 = Dense(13, activation='relu')(input_layer)
layer2 = Dense(7, activation='relu')(layer1)

# Define output layer
output_layer = Dense(1, activation='sigmoid')(layer2)

# Create the model
model_func = Model(inputs=input_layer, outputs=output_layer)

# Compile the functional model
model_func.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

# Train the functional model
model_func.fit(x=data, y=labels, epochs=10, batch_size=10)

# Evaluate the functional model
train_loss, train_acc = model_func.evaluate(x=data, y=labels)
test_loss, test_acc = model_func.evaluate(x=data_test, y=labels_test)

print(f"[Functional] Training Accuracy: {train_acc:.4f}, Training Loss: {train_loss:.4f}")
print(f"[Functional] Test Accuracy: {test_acc:.4f}, Test Loss: {test_loss:.4f}")


Epoch 1/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5674 - loss: 0.6866  
Epoch 2/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5661 - loss: 0.6923 
Epoch 3/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5686 - loss: 0.6980 
Epoch 4/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5539 - loss: 0.6975 
Epoch 5/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5464 - loss: 0.6998 
Epoch 6/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5395 - loss: 0.6981 
Epoch 7/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5262 - loss: 0.6960 
Epoch 8/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5509 - loss: 0.6919 
Epoch 9/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4942 - loss: 0.7068 
Epoch 10/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5405 - loss: 0.6925 
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5339 - loss: 0.6932  
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.4000 - loss: 0.7005
[Fu

<h2>MNIST digit classification using
TensorFlow 2.0</h2>

In [6]:
#Importing the libraries
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf
print (tf.__version__)

2.19.0


In [7]:
#loading the dataset
mnist =  tf.keras.datasets.mnist

In [8]:
# creating a train and test set:
(x_train,y_train), (x_test, y_test) = mnist.load_data()
# Normalizing the x values by diving with maximum value of x which is 255 and convert them to float:
x_train, x_test = tf.cast(x_train/255.0, tf.float32), tf.cast(x_test/255.0, tf.float32)
# converting y values to int:
y_train, y_test = tf.cast(y_train,tf.int64),tf.cast(y_test,tf.int64)
# Defining the sequential model:
model = tf.keras.models.Sequential()

In [9]:
# Adding the layers. applying ReLU activation at the first two layers 
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(256, activation="relu"))
model.add(tf.keras.layers.Dense(128, activation="relu"))
#applying softmax function in the final layer
model.add(tf.keras.layers.Dense(10, activation="softmax"))


In [10]:
# Compiling the model with Stochastic Gradient Descent, that is 'sgd' 

model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# Train the model for 10 epochs with batch_size as 32:
model.fit(x_train, y_train, batch_size=32, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7346 - loss: 1.0275
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9153 - loss: 0.2962
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9327 - loss: 0.2394
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9445 - loss: 0.1978
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9512 - loss: 0.1730
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9576 - loss: 0.1489
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9612 - loss: 0.1366
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9671 - loss: 0.1198
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9681 - loss: 0.1123
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9695 - loss: 0.1055


In [11]:
#evaluating the model on test sets
model.evaluate(x_test, y_test)


313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9612 - loss: 0.1321


[0.1109575554728508, 0.9664000272750854]